export const sampleProperties = [
  {
    id: "p1",
    title: "The Sovereign Villa",
    slug: "the-sovereign-villa",
    description: "A luxury estate offering breathtaking views and modern amenities.",
    price: "₹150 Lakhs",
    price_value: 150,
    location: "Kakadeo, Kanpur",
    city: "Kanpur",
    property_type: "Villa",
    purpose: "For Sale",
    status: "Available",
    beds: 4,
    baths: 4,
    area: "3200 sq.ft",
    badge: "Featured",
    featured: true,
    published: true,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format"],
    amenities: ["Swimming Pool", "Garden", "Garage", "Smart Home"],
    nearby: ["City Mall (2km)", "International School (1km)"],
    location_advantages: ["High Appreciation Rate", "Premium Neighborhood"],
    investment_highlights: ["Expected 12% ROI"],
    google_maps_link: "",
    youtube_link: "",
    meta_title: "The Sovereign Villa",
    meta_description: "Luxury villa in Kanpur",
    created_at: new Date().toISOString()
  },
  {
    id: "p2",
    title: "Crestview Apartments",
    slug: "crestview-apartments",
    description: "Modern living space with state-of-the-art facilities.",
    price: "₹85 Lakhs",
    price_value: 85,
    location: "Swaroop Nagar, Kanpur",
    city: "Kanpur",
    property_type: "Apartment",
    purpose: "For Sale",
    status: "Available",
    beds: 3,
    baths: 2,
    area: "1800 sq.ft",
    badge: "New",
    featured: true,
    published: true,
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&auto=format"],
    amenities: ["Gym", "Security 24/7", "Power Backup", "Club House"],
    nearby: ["Metro Station (0.5km)", "Hospital (1km)"],
    location_advantages: ["Prime Location", "Excellent Connectivity"],
    investment_highlights: ["High Rental Yield"],
    google_maps_link: "",
    youtube_link: "",
    meta_title: "Crestview Apartments",
    meta_description: "Premium apartments in Swaroop Nagar",
    created_at: new Date().toISOString()
  },
  {
    id: "p3",
    title: "Golden Aura Commercial",
    slug: "golden-aura-commercial",
    description: "Premium office space in the heart of the city.",
    price: "Price on Request",
    price_value: 0,
    location: "Civil Lines, Kanpur",
    city: "Kanpur",
    property_type: "Office",
    purpose: "Commercial",
    status: "Available",
    beds: 0,
    baths: 2,
    area: "5000 sq.ft",
    badge: "Exclusive",
    featured: true,
    published: true,
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format"],
    amenities: ["Central AC", "Parking", "Cafeteria", "Conference Rooms"],
    nearby: ["Banks (0.1km)", "Restaurants (0.2km)"],
    location_advantages: ["Business Hub", "High Visibility"],
    investment_highlights: ["Corporate Tenant Friendly"],
    google_maps_link: "",
    youtube_link: "",
    meta_title: "Golden Aura Commercial",
    meta_description: "Office space in Civil Lines",
    created_at: new Date().toISOString()
  }
];

export const sampleBlogs = [
  {
    id: "b1",
    title: "Top 5 Neighborhoods for Investment in Kanpur",
    slug: "top-5-neighborhoods",
    description: "Discover the best areas to invest in real estate in Kanpur for maximum returns.",
    content: "Kanpur is growing rapidly, and certain neighborhoods are showing incredible potential...",
    featured_image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&auto=format",
    category: "Investment",
    publish_date: "2024-10-15",
    published: true,
    meta_title: "Top 5 Neighborhoods in Kanpur",
    meta_description: "Investment guide for Kanpur",
    created_at: new Date().toISOString()
  },
  {
    id: "b2",
    title: "Why Luxury Real Estate is Booming",
    slug: "why-luxury-real-estate-is-booming",
    description: "An analysis of the current market trends favoring luxury property investments.",
    content: "Post-pandemic, there has been a significant shift towards luxury and spacious homes...",
    featured_image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format",
    category: "Market Trends",
    publish_date: "2024-11-02",
    published: true,
    meta_title: "Luxury Real Estate Boom",
    meta_description: "Trends in luxury real estate",
    created_at: new Date().toISOString()
  },
  {
    id: "b3",
    title: "A Guide to Buying Your First Villa",
    slug: "guide-to-buying-first-villa",
    description: "Everything you need to know before making your first premium real estate purchase.",
    content: "Buying a villa is a significant milestone. Here are the things you should look out for...",
    featured_image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format",
    category: "Guides",
    publish_date: "2024-11-20",
    published: true,
    meta_title: "Buying First Villa",
    meta_description: "Villa buying guide",
    created_at: new Date().toISOString()
  }
];

export const sampleTestimonials = [
  {
    id: "t1",
    name: "Rajesh Kumar",
    designation: "Business Owner",
    rating: 5,
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format",
    testimonial: "Royal Properties found exactly what I was looking for. The professionalism and transparency throughout the process were outstanding.",
    created_at: new Date().toISOString()
  },
  {
    id: "t2",
    name: "Anita Sharma",
    designation: "Doctor",
    rating: 5,
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format",
    testimonial: "Moving to Kanpur was made seamless thanks to their expert guidance. They understand luxury and customer needs perfectly.",
    created_at: new Date().toISOString()
  },
  {
    id: "t3",
    name: "Vikram Singh",
    designation: "Corporate Executive",
    rating: 4,
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format",
    testimonial: "Excellent service from start to finish. The team at Royal Properties is knowledgeable and genuinely cares about finding the right fit.",
    created_at: new Date().toISOString()
  }
];
